const express = require('express')
const router = express.Router()
const { getDashboard } = require('../controllers/dashboardController')
const { listProducts, createProduct, updateProduct, deleteProduct } = require('../controllers/productController')
const { createSale, listSales, deleteSale } = require('../controllers/saleController')
const { listDamages, createDamage, deleteDamage, getDamageReport } = require('../controllers/damageController')
const { getReport } = require('../controllers/reportController')
const { listServices, createService, updateService, deleteService, createServiceBill, listServiceBills } = require('../controllers/serviceController')
const { getSettings, updateSettings, backupData, restoreData } = require('../controllers/settingController')
const { verifyProductsPassword } = require('../controllers/authController')
const { listMonthlyCosts, createMonthlyCost, deleteMonthlyCost } = require('../controllers/monthlyCostController')
const { login, logout, changePassword, getProfile, listUsers, createUser, updateUser, resetPassword, deleteUser, requestSalesmanSignup } = require('../controllers/userController')
const { verifyToken, authorizeRole, attachUser } = require('../middleware/auth')
const { validateRequest, loginValidation, registerValidation } = require('../middleware/validation')

router.use(attachUser)

router.post('/auth/login', loginValidation, validateRequest, login)
router.post('/auth/signup/salesman', registerValidation, validateRequest, requestSalesmanSignup)
router.post('/auth/logout', verifyToken, logout)
router.post('/auth/change-password', verifyToken, changePassword)
router.get('/auth/me', verifyToken, getProfile)
router.get('/auth/users', verifyToken, authorizeRole('admin'), listUsers)
router.post('/auth/users', verifyToken, authorizeRole('admin'), registerValidation, validateRequest, createUser)
router.put('/auth/users/:id', verifyToken, authorizeRole('admin'), updateUser)
router.delete('/auth/users/:id', verifyToken, authorizeRole('admin'), deleteUser)
router.post('/auth/users/:id/reset-password', verifyToken, authorizeRole('admin'), resetPassword)
router.post('/auth/verify-products-password', verifyProductsPassword)

router.get('/dashboard', verifyToken, authorizeRole('admin'), getDashboard)
router.get('/products', verifyToken, authorizeRole('admin', 'salesman'), listProducts)
router.post('/products', verifyToken, authorizeRole('admin'), createProduct)
router.put('/products/:id', verifyToken, authorizeRole('admin'), updateProduct)
router.delete('/products/:id', verifyToken, authorizeRole('admin'), deleteProduct)
router.post('/sales', verifyToken, authorizeRole('admin', 'salesman'), createSale)
router.get('/sales', verifyToken, authorizeRole('admin', 'salesman'), listSales)
router.delete('/sales/:id', verifyToken, authorizeRole('admin'), deleteSale)
router.get('/damages', verifyToken, authorizeRole('admin', 'salesman'), listDamages)
router.post('/damages', verifyToken, authorizeRole('admin', 'salesman'), createDamage)
router.delete('/damages/:id', verifyToken, authorizeRole('admin', 'salesman'), deleteDamage)
router.get('/damages/report', verifyToken, authorizeRole('admin'), getDamageReport)
router.get('/reports/:type', verifyToken, authorizeRole('admin'), getReport)
router.get('/services', verifyToken, authorizeRole('admin', 'salesman'), listServices)
router.post('/services', verifyToken, authorizeRole('admin', 'salesman'), createService)
router.put('/services/:id', verifyToken, authorizeRole('admin', 'salesman'), updateService)
router.delete('/services/:id', verifyToken, authorizeRole('admin', 'salesman'), deleteService)
router.post('/service-bills', verifyToken, authorizeRole('admin', 'salesman'), createServiceBill)
router.get('/service-bills', verifyToken, authorizeRole('admin', 'salesman'), listServiceBills)
router.get('/settings', verifyToken, authorizeRole('admin', 'salesman'), getSettings)
router.put('/settings', verifyToken, authorizeRole('admin'), updateSettings)
router.get('/settings/backup', verifyToken, authorizeRole('admin'), backupData)
router.post('/settings/restore', verifyToken, authorizeRole('admin'), restoreData)
router.get('/monthly-costs', verifyToken, authorizeRole('admin'), listMonthlyCosts)
router.post('/monthly-costs', verifyToken, authorizeRole('admin'), createMonthlyCost)
router.delete('/monthly-costs/:id', verifyToken, authorizeRole('admin'), deleteMonthlyCost)

module.exports = router
