const express = require('express')
const router = express.Router()
const { getDashboard } = require('../controllers/dashboardController')
const { listProducts, createProduct, updateProduct, deleteProduct } = require('../controllers/productController')
const { createSale, listSales, deleteSale } = require('../controllers/saleController')
const { listDamages, createDamage, deleteDamage, getDamageReport } = require('../controllers/damageController')
const { getReport } = require('../controllers/reportController')
const { listServices, createService, updateService, deleteService, createServiceBill, listServiceBills } = require('../controllers/serviceController')
const { getSettings, updateSettings, backupData, restoreData } = require('../controllers/settingController')
const { verifyProductsPassword } = require('../controllers/authController')

router.get('/dashboard', getDashboard)
router.get('/products', listProducts)
router.post('/products', createProduct)
router.put('/products/:id', updateProduct)
router.delete('/products/:id', deleteProduct)
router.post('/sales', createSale)
router.get('/sales', listSales)
router.delete('/sales/:id', deleteSale)
router.get('/damages', listDamages)
router.post('/damages', createDamage)
router.delete('/damages/:id', deleteDamage)
router.get('/damages/report', getDamageReport)
router.get('/reports/:type', getReport)
router.get('/services', listServices)
router.post('/services', createService)
router.put('/services/:id', updateService)
router.delete('/services/:id', deleteService)
router.post('/service-bills', createServiceBill)
router.get('/service-bills', listServiceBills)
router.get('/settings', getSettings)
router.put('/settings', updateSettings)
router.get('/settings/backup', backupData)
router.post('/settings/restore', restoreData)
router.post('/auth/verify-products-password', verifyProductsPassword)

module.exports = router
